---
- name: Prepare
  hosts: all
  vars:
    php_repos:
      - "deb https://packages.sury.org/php {{ ansible_distribution_release }} main"
      - "deb-src https://packages.sury.org/php {{ ansible_distribution_release }} main"
    php_packages:
      - php7.4-fpm
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present
        update_cache: true

    - name: Add php repository key
      apt_key:
        url: "https://packages.sury.org/php/apt.gpg"
        state: present

    - name: Add php repository repos (Debian)
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ php_repos }}"
      when: ansible_distribution == "Debian"

    - name: Add php repository repos (Ubuntu)
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install php
      apt:
        name: "{{ php_packages }}"
        state: present
